### ISSUE TITLE
Sounds weird when the input is short

### ISSUE THREAD

**Issue by harryfyodor** [yl4579/StyleTTS#16]
Hi, I find that the model produces really great outputs when synthesizing sentences of medium or long length. However, when synthesizing short sentences or words, the audio sounds weird. For example, I used the pretrained LibriTTS model to synthesize the word “people” (IPA: pˈiːpəl). No matter what reference audio I gave, long or short, the output was weird, especially at the end of the word. This phenomenon occurred when the input was short. I attached an example audio here [people.wav.zip.](https://github.com/yl4579/StyleTTS/files/10880179/people.wav.zip) Do you have any methods to solve or alleviate this problem? Thank you very much!

**Comment by yl4579** [comment]
This is likely because of the training data we used. During training, we skipped samples that are less than one second (less than 80 frames) because of the pooling layers in the style encoder (i.e., if the input is less than one second, the second last feature map will be too small to go through the last residual layer). The model has never been trained to synthesize speech less than one second, so it may not be able to generate natural speech under that duration. 

You need to either retrain the model with padded or repeated input for the style encoder, or you can add some phonemes during inference to make the sentence you want to synthesize longer and trim the synthesized results based on the predicted duration to the part you want.
