### ISSUE TITLE
finetune the vocoder

### ISSUE THREAD

**Issue by sinhprous1** [yl4579/StyleTTS#17]
Hi @yl4579 , thanks for you amazing work. 
I want to finetune the HifiGAN model, but seems the pretrained weight only has generator. Could you also publish the discriminator? Thanks.

**Comment by yl4579** [comment]
Here is the discriminator for the vocoder trained on the LibriTTS dataset (the most general one that you can fine-tune on any dataset): https://drive.google.com/file/d/1l9FJV2kVItd8wwNWS4L4CYGuCx0SbsUw/view?usp=sharing

By the way, I'm working on the recipe with the official HifiGAN and BIGVGAN configurations now, so if you are also interested in that, stay tuned. They are 22050 Hz, though, and my configuration is 24000 Hz. If you prefer to work with audios in 24 kHz, maybe you can directly fine-tune my model. However, I found my HifiGAN model sounds slightly worse than their checkpoint for some reason, maybe due to not tuning the hyperparameters carefully.

**Comment by crypticsymmetry** [comment]
How's the progress with BigVGAN coming? Any idea on when it will be added?

**Comment by lexkoro** [comment]
@crypticsymmetry I am currently testing StyleTTS in combination with BigVGAN myself. 
I've added my modifications in here https://github.com/lexkoro/StyleTTS

Currently training stage2 of StyleTTS (multispeaker) but the speaker similarity is quite bad so far, so I am not sure if I've messed up somewhere or it just needs more training.

**Comment by yl4579** [comment]
@crypticsymmetry It worked for me on LJSpeech, but I don't have enough time to train on LibriTTS. I will test on multispeaker using VCTK dataset and see if it works well on that as well.

@lexkoro Not sure why stage 2 matters for speaker similarity, as that should only depend on stage 1 (acoustic model).

**Comment by sinhprous** [comment]
Thanks @yl4579 , the vocoder discriminator works for me and I can use it to finetune the vocoder for StyleTTS.
Btw, do you have  pre-trained model for ESD dataset?
