### ISSUE TITLE
train from scratch of another phoneme set

### ISSUE THREAD

**Issue by zdj97** [yl4579/StyleTTS#24]
if i want to train the repo in Chinese with another phoneme set not like pypinyin, what do i need to do ? thanks!

**Comment by yl4579** [comment]
You need to train a text aligner first, see https://github.com/yl4579/AuxiliaryASR
But if you want to IPA, for example, you do not need to train your own text aligner. You can just use what I have provided here.

**Comment by leminhnguyen** [comment]
@yl4579 It means if I train in another language and still use IPA characters I can use the pre-trained text aligner? If that's right, what about the alignment accuracy? Because the pre-trained ASR was for English.

**Comment by yl4579** [comment]
The aligner in this repo was not just English. It was pre-trained on English, Japanese, Spanish, and Mandarin Chinese datasets, so it covers a wide range of IPAs. If the target language still differs significantly from these four languages (for example, Hindi, German, and Persian should be fine because they are phonetically close to these four languages, but Arabic might be a little difficult), you still need to retrain the text aligner.

**Comment by yl4579** [comment]
@leminhnguyen The aligner in this repo was not just English. It was pre-trained on English, Japanese, Spanish, and Mandarin Chinese datasets, so it covers a wide range of IPAs. If the target language still differs significantly from these four languages (for example, Hindi, German, and Persian should be fine because they are phonetically close to these four languages, but Arabic might be a little difficult), you still need to retrain the text aligner.

**Comment by leminhnguyen** [comment]
Thanks @yl4579, I will try to use the pre-trained ASR model for Vietnamese.

**Comment by nhanhttrong** [comment]
@leminhnguyen I wonder if you have trained in Vietnamese yet. If you have already trained, can you provide the pre-train model?
Thank you very much ?
