### ISSUE TITLE
Questions about the Evaluations

### ISSUE THREAD

**Issue by malu01** [yl4579/StyleTTS#39]
StyleTTS's ref mel requires a single audio as input, which may result in the style vector only being similar to the ref wav, but somewhat different from other waves of the same speaker. May I ask if the ref mel you use for evaluations is gt or randomly selected from the dataset during your evaluation stage?

**Comment by yl4579** [comment]
If you meant the samples in the "Zero-Shot Speaker Adaptation" section on the demo page [here](https://styletts.github.io/#vctk), it is randomly selected from the dataset (not included on the demo page because all samples are very similar to each other in the VCTK dataset). For more samples you can refer to the StyleTTS 2 demo page that includes samples generated by StyleTTS LibriTTS model and the reference audio: https://styletts2.github.io/
