### ISSUE TITLE
style encoder inconsistency

### ISSUE THREAD

**Issue by auspicious3000** [yl4579/StyleTTS#55]
Hello,

In train_first.py, 

`s = model.style_encoder(gt.unsqueeze(1))`

However, in train_second.py, 

```
 # compute the style of the entire utterance
 # this operation cannot be done in batch because of the avgpool layer (may need to work on masked avgpool)
 ss = []
 for bib in range(len(mel_input_length)):
     mel_length = int(mel_input_length[bib].item())
     mel = mels[bib, :, :mel_input_length[bib]]
     s = model.style_encoder(mel.unsqueeze(0).unsqueeze(1))
     ss.append(s)
 s = torch.stack(ss).squeeze()
```

The batched output and per-utterance output are indeed different. Why are train_first and trans_second inconsistent in the ways of extracting style embedding? Since "this operation cannot be done in batch", why it is done in batch in train_first.py?

Thanks for your help!

**Comment by yl4579** [comment]
This `s` is used for duration prediction, which is utterance-wise (rather than clip-wise), as you are predicting the durations for the entire utterance rather than just some clip. If you scroll down you can see that the `s` used for F0 prediction is the same as the `s` in train_first.py because then you are doing per-clip F0 prediction instead of per-utterance prediction.
