### ISSUE TITLE
train on ESD

### ISSUE THREAD

**Issue by bobo-paopao** [yl4579/StyleTTS#63]
Use the English speaker data set in the ESD data set for training. After the first stage of 200 epoch training, the MEL-loss is about 0.17. Then after the second stage of training, we tested and found that the synthesized speech effect was very poor. Let’s continue now. In the first stage of training, mel-loss has declined to a certain extent. I would like to ask how many epochs of training are needed to achieve the effect you showed?

**Comment by yl4579** [comment]
Have you tried to just do reconstruction (i.e. turn the reconstructed mel into waveform and listen to them)? What does it sound like? Also, by "poor", do you mean the sound quality is bad, or the prosody is bad? If it is the former, it could be because of the vocoder, as 200 epochs should definitely be enough for 10 English speakers. You should use the vocoder trained on LibriTTS for this task. If it is the latter, maybe the second stage is not trained for enough epochs.
